PACKAGE_NAME="K6602VV-fan"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="K6602VV_fan"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
